name: Deploy static content to Pages

on:
  push:
    branckes: 
      - master

permissions:
  contents: read
  pages: write
  id-token: write

default:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./html"

