name: Static Site Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@main
      with:
        branch: master
        folder: html
    env:
      name: github-pages
      url: https://bonfire8458.github.io/test2/

